version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


# docker run -d \
#   --name pgvector-db \
#   -e POSTGRES_USER= \
#   -e POSTGRES_PASSWORD= \
#   -e POSTGRES_DB=mdb \
#   -p 5432:5432 \
#   pgvector/pgvector:pg17